module.exports = {
  Dacs: [
    {
      id: 0,
      name: "",
      maxPCM: "",
      maxDSD: "",
      interface: "",
      imageURL: "",
      URL: "",
    },
    {
      id: 1,
      name: "VMV D1SE",
      maxPCM: "768Khz",
      maxDSD: "22.4Mhz",
      interface: "D1SE",
      imageURL: "http://auro/img/dacs/vmv-d1se.png",
      URL: "https://www.smsl-audio.com/portal/product/detail/id/742.html",
    },
    {
      id: 2,
      name: "Gustard X16",
      maxPCM: "768Khz",
      maxDSD: "22.4Mhz",
      interface: "Gustard USB Audio 2.0",
      imageURL: "http://auro/img/dacs/gustard-x16.png",
      URL: "http://www.gustard.cn/?post_type=products&page_id=8938",
    },
    {
      id: 3,
      name: "Topping D10",
      maxPCM: "384Khz",
      maxDSD: "11.2Mhz",
      interface: "D10",
      imageURL: "http://auro/img/dacs/topping-d10.png",
      URL: "https://www.audiosciencereview.com/forum/index.php?threads/review-and-measurements-of-topping-d10-dac.2470/",
    },
  ],
  Services: [
    {
      id: "SRV-01",
      name: "Spotify Connect",
      creator: "Auro",
      description: "Stream via Spotify",
      image: "http://auro/img/spotify-img.png",
      extension: "spotify",
    },
    {
      id: "SRV-02",
      name: "Tidal Connect",
      creator: "Auro",
      description: "Stream via Tidal",
      image: "http://auro/img/tidal-img.png",
      extension: "tidal",
    },
    {
      id: "SRV-03",
      name: "Roon Bridge",
      creator: "Auro",
      description: "Stream via Roon",
      image: "http://auro/img/roon-img.png",
      extension: "roon",
    },
    {
      id: "SRV-04",
      name: "HQPlayer NAA",
      creator: "Auro",
      description: "Stream via HQPlayer",
      image: "http://auro/img/hqplayer-img.png",
      extension: "naa",
    },
    {
      id: "SRV-05",
      name: "Airplay",
      creator: "Auro",
      description: "Stream via Airplay",
      image: "http://auro/img/airplay-img.png",
      extension: "airplay",
    },
    {
      id: "SRV-06",
      name: "DLNA",
      creator: "Auro",
      description: "Stream via DLNA",
      image: "http://auro/img/dlna-img.png",
      extension: "dlna",
    },
    {
      id: "SRV-07",
      name: "DLNA Bridge",
      creator: "Auro",
      description: "DLNA via LMS",
      image: "http://auro/img/upnp_dlna-img.jpg",
      extension: "dlnaBridge",
    },
  ],
};
